<?php

/**
 * @file
 * supress_helper.module
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Installer\InstallerKernel;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Site\Settings;
use Drupal\media\MediaInterface;
use Drupal\migrate\Plugin\MigrateSourceInterface;
use Drupal\migrate\Plugin\MigrationInterface;
use Drupal\migrate\Row;
use Drupal\node\NodeInterface;
use Drupal\search_api\IndexInterface;
use Drupal\Component\Utility\UrlHelper;

/**
 * Implements hook_migration_plugins_alter().
 */
function supress_helper_migration_plugins_alter(array &$migrations) {
  foreach ($migrations as &$migration) {
    $firstUrl = $migration['source']['urls'][0] ?? '';

    if (!str_starts_with($firstUrl, 'https://memento.stanford.edu')) {
      continue;
    }
    /** @var \Drupal\supress_helper\PressHelperInterface $service */
    $service = \Drupal::service('supress_helper');
    $migration['source']['urls'] = $service->getMigrationUrls($firstUrl);
  }
}

/**
 * Implements hook_page_attachments().
 */
function supress_helper_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'supress_helper/admin';
}

/**
 * Implements hook_library_info_alter().
 */
function supress_helper_library_info_alter(&$libraries, $extension) {
  if ($extension === 'ckeditor5') {
    $module_path = \Drupal::service('extension.list.module')
      ->getPath('supress_helper');
    $libraries['internal.drupal.ckeditor5.stylesheets'] = [
      'css' => [
        'theme' => [
          "/$module_path/styles/dist/css/ckeditor.css" => [],
        ],
      ],
    ];
  }
}

/**
 * Implements hook_paragraphs_behavior_info_alter().
 */
function supress_helper_paragraphs_behavior_info_alter(&$paragraphs_behavior) {
  $paragraphs_behavior['su_card_styles']['class'] = '\Drupal\supress_helper\Plugin\paragraphs\Behavior\PressCardBehaviors';
}

/**
 * Implements hook_ENTITY_TYPE_access().
 */
function supress_helper_media_access(MediaInterface $media, $operation, AccountInterface $account) {
  $route = \Drupal::routeMatch()->getRouteName();
  return AccessResult::forbiddenIf($route != 'graphql.query.graphql_compose_server' && $media->bundle() == 'sup_protected_file' && $account->isAnonymous());
}

/**
 * Implements hook_cron().
 */
function supress_helper_cron() {
  /** @var \Drupal\supress_helper\PressHelperInterface $service */
  $service = \Drupal::service('supress_helper');
  $service->queueCoverImages();
}

/**
 * Implements hook_search_api_algolia_objects_alter().
 */
function supress_helper_search_api_algolia_objects_alter(array &$objects, IndexInterface $index, array $items) {
  $term_storage = \Drupal::entityTypeManager()->getStorage('taxonomy_term');
  foreach ($objects as &$object) {
    // Useful to limit record data for local algolia testing.
    if (Settings::get('algolia_limit_record')) {
      $object['html'] = implode(' ', array_slice(explode(' ', $object['html'] ?? ''), 0, 10));
    }

    if (isset($object['book_subject'])) {
      $object['book_subject'] = is_array($object['book_subject']) ? $object['book_subject'] : [$object['book_subject']];
      $all_subjects = [];

      foreach ($object['book_subject'] as &$term_id) {
        $term = $term_storage->load($term_id);
        $all_subjects[] = $term->label();
        while ($parent = $term_storage->loadParents($term_id)) {
          $term = reset($parent);
          $all_subjects[] = $term->label();
          $term_id = $term->id();
        }
        $term_id = $term->label();
      }

      asort($all_subjects);
      asort($object['book_subject']);
      $object['book_subject_all'] = $all_subjects;
      $object['book_subject'] = array_values(array_unique($object['book_subject']));
    }
  }
}

/**
 * Implements hook_entity_create_access().
 */
function supress_helper_entity_create_access(AccountInterface $account, array $context, $entity_bundle) {
  // Disable the banner paragraph type.
  return AccessResult::forbiddenIf($entity_bundle == 'stanford_banner');
}

/**
 * Implements hook_field_widget_complete_WIDGET_TYPE_form_alter().
 */
function supress_helper_field_widget_complete_options_select_form_alter(&$field_widget_complete_form, FormStateInterface $form_state, $context) {
  if ($context['items']->getName() == 'sup_search_subject') {
    // Only show the top level terms and the "None" option.
    $field_widget_complete_form['widget']['#options'] = array_filter($field_widget_complete_form['widget']['#options'], fn($option) => !str_starts_with($option, '-') || $option == '- None -');
  }
}

/**
 * Implements hook_migrate_prepare_row().
 */
function supress_helper_migrate_sup_import_books_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {
  $row->setSourceProperty('current_feed_url', NULL);
  $id_map = $row->getIdMap();
  if (!isset($id_map['sourceid1'])) {
    return;
  }
  $retailers = _supress_get_ebook_retailers();
  $retailers = array_filter($retailers, fn($retailer) => (int) $retailer['work_id_number'] == (int) $id_map['sourceid1']);
  $row->setSourceProperty('ebook_retailers', array_values($retailers));

  $book_formats = _supress_ebook_formats();
  $row->setSourceProperty('epub', $book_formats[$id_map['sourceid1']]['epub'] ?? NULL);
  $row->setSourceProperty('pdf', $book_formats[$id_map['sourceid1']]['pdf'] ?? NULL);
}

/**
 * Get a list of all books with epub or pdf formats.
 *
 * @return array
 *   Keyed array of work id and it's respective formats.
 */
function _supress_ebook_formats(): array {
  $cache = \Drupal::cache();
  if ($cached_item = $cache->get('filemaker_ebook_formats')) {
    return $cached_item->data;
  }
  $search_body = [
    'query' => [
      ['format_pdf' => '=yes'],
      ['format_epub' => '=yes'],
    ],
  ];
  try {
    $formats = _supress_search_filemaker('https://memento.stanford.edu/fmi/data/v2/databases/Web/layouts/EbookRetailers/_find', $search_body, 10000);
  }
  catch (\Exception $e) {
    \Drupal::logger('supress')
      ->error('An error occurred when fetching ebook formats: @error', ['@error' => $e->getMessage()]);
    $formats = [];
  }

  $book_formats = [];
  foreach ($formats as $item) {
    if (empty($book_formats[(int) $item['fieldData']['work_id_number']]['epub'])) {
      $book_formats[(int) $item['fieldData']['work_id_number']]['epub'] = $item['fieldData']['format_epub'] == 'yes';
    }

    if (empty($book_formats[(int) $item['fieldData']['work_id_number']]['pdf'])) {
      $book_formats[(int) $item['fieldData']['work_id_number']]['pdf'] = $item['fieldData']['format_pdf'] == 'yes';
    }
  }
  ksort($book_formats);

  $cache->set('filemaker_ebook_formats', $book_formats, time() + 60 * 60 * 24);
  return $book_formats;
}

/**
 * Get the list of all ebooks from the FileMaker API.
 *
 * @return array
 *   Array of retailer data.
 */
function _supress_get_ebook_retailers() {
  $cache = \Drupal::cache();
  if ($cached_item = $cache->get('filemaker_ebook_retailers')) {
    return $cached_item->data;
  }
  $search_body = [
    'query' => [['link' => 'http']],
    'sort' => [['fieldName' => 'retailer', 'sortOrder' => 'ascend']],
  ];
  try {
    $retailers = _supress_search_filemaker('https://memento.stanford.edu/fmi/data/v2/databases/Web/layouts/EbookRetailers/_find', $search_body, 10000);
  }
  catch (\Exception $e) {
    \Drupal::logger('supress')
      ->error('An error occurred when fetching ebook retailer links: @error', ['@error' => $e->getMessage()]);
    $retailers = [];
  }

  foreach ($retailers as &$record) {
    $record = [
      'work_id_number' => $record['fieldData']['work_id_number'],
      'title' => $record['fieldData']['retailer'],
      'uri' => trim($record['fieldData']['link']),
    ];
  }
  $retailers = array_filter($retailers, fn($item) => UrlHelper::isValid($item['uri']));

  $cache->set('filemaker_ebook_retailers', $retailers, time() + 60 * 60 * 24);
  return $retailers;
}

/**
 * Perform a search on the filemaker API and return all records.
 *
 * @param string $endpoint
 *   API endpoint, should end in `_find`.
 * @param array $body
 *   Keyed array of search parameters.
 * @param int $limit
 *   Page limit per request.
 *
 * @return array
 *   Array of all records returned in the search.
 *
 * @see https://help.claris.com/en/data-api-guide/content/perform-find-request.html
 */
function _supress_search_filemaker(string $endpoint, array $body, int $limit = 1000): array {
  /** @var \Drupal\supress_helper\PressHelperInterface $service */
  $service = \Drupal::service('supress_helper');
  $token = $service->getApiToken();

  if (!$token) {
    return [];
  }

  $client = \Drupal::httpClient();
  $fetch_more = TRUE;
  $page = 0;
  $return_data = [];

  $body['limit'] = $limit;

  while ($fetch_more) {
    $body['offset'] = ($page * $limit) + 1;
    $ebook_retailers_page = (string) $client->request('POST', $endpoint, [
      'headers' => [
        'Content-Type' => 'application/json',
        'Authorization' => 'Bearer ' . $token,
      ],
      'body' => json_encode($body),
      'timeout' => 60,
    ])->getBody();
    $ebook_retailers_page = json_decode($ebook_retailers_page, TRUE);

    $return_data = [
      ...$return_data,
      ...$ebook_retailers_page['response']['data'],
    ];

    $fetch_more = $ebook_retailers_page['response']['dataInfo']['returnedCount'] == $limit;
    $page++;
  }

  return $return_data;
}

/**
 * Implements hook_field_widget_single_element_form_alter().
 */
/**
 * Implements hook_field_widget_single_element_WIDGET_TYPE_form_alter().
 */
function supress_helper_field_widget_single_element_viewfield_select_form_alter(array &$element, FormStateInterface $form_state, array $context) {
  $element['view_options']['helper'] = [
    '#type' => 'container',
    'help_text' => [
      '#markup' => t('Book view arguments should be constructed like %subject/%series/%tags/%imprints/%work. To skip an argument, provide an empty quotes: "".', [
        '%subject' => 'subject-term-names',
        '%series' => 'series-term-names',
        '%tags' => 'book-tag-names',
        '%imprints' => 'book-imprint-names',
        '%work' => 'work+id+numbers',
      ]),
    ],
    '#weight' => 21,
    '#states' => [
      'visible' => [
        '[name="su_list_view[0][display_id]"]' => [
          ['value' => 'award_winners'],
          ['value' => 'book_list'],
        ],
      ],
    ],
  ];

  $element['view_options']['seasonal_helper'] = [
    '#type' => 'container',
    'help_text' => [
      '#markup' => t('The argument should be the exact string of the "Catalog Season" field'),
    ],
    '#weight' => 21,
    '#states' => [
      'visible' => [
        '[name="su_list_view[0][display_id]"]' => ['value' => 'seasonal_list'],
      ],
    ],
  ];
}
