<?php

/**
 * @file
 * supress_helper.install
 */

use Drupal\field\Entity\FieldStorageConfig;
use Drupal\field\Entity\FieldConfig;

/**
 * Move search exclude field value
 */
function supress_helper_update_9012() {
  $field_storage = FieldStorageConfig::loadByName('node', 'su_search_exclusion');
  if (!$field_storage) {
    $field_storage = FieldStorageConfig::create([
      'uuid' => '6c547417-9862-490a-b1e5-8e1b3abaf2fd',
      'field_name' => 'su_search_exclusion',
      'entity_type' => 'node',
      'type' => 'search_api_exclude_entity',
      'cardinality' => 1,
    ]);
    $field_storage->save();
  }

  $field = FieldConfig::loadByName('node', 'stanford_page', 'su_search_exclusion');
  if (!$field) {
    FieldConfig::create([
      'uuid' => '505979e7-eac5-4712-bd77-0bd40c88d80a',
      'field_storage' => $field_storage,
      'bundle' => 'stanford_page',
      'label' => 'Search Exclusion',
    ])->save();
  }
  $ns = \Drupal::entityTypeManager()->getStorage('node');
  $nids = $ns->getQuery()
    ->accessCheck(FALSE)
    ->condition('type', 'stanford_page')
    ->condition('sup_page_search_exclude', 1)
    ->execute();

  foreach ($ns->loadMultiple($nids) as $node) {
    $node->set('su_search_exclusion', TRUE);
    $node->save();
  }
}
