github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: false
    addComment: false
    addBadge: false
ports:
  - port: 3306
    onOpen: ignore
    visibility: private
  - port: 33060
    onOpen: ignore
    visibility: private
  - port: 8001
    onOpen: ignore
    visibility: public
  - port: 3000
    onOpen: ignore
    visibility: public
image: pookmish/drupal8ci:gitpod
tasks:
  - before: >
      rm -rf ~/.ssh/id_rsa &&
      rm -rf ~/.ssh/id_rsa.pub &&
      eval $(command gp env -e) &&
      mkdir -p ~/.ssh &&
      [[ ! -z $SSH_PUBLIC_KEY  ]] &&
      echo $SSH_PUBLIC_KEY | base64 -d > ~/.ssh/id_rsa.pub &&
      chmod 644 ~/.ssh/id_rsa.pub &&
      [[ ! -z $SSH_PRIVATE_KEY  ]] &&
      echo $SSH_PRIVATE_KEY | base64 -d > ~/.ssh/id_rsa &&
      chmod 600 ~/.ssh/id_rsa &&
      [[ ! -z $GITCONFIG  ]] &&
      echo $GITCONFIG | base64 -d > ~/.gitconfig &&
      chmod 644 ~/.gitconfig
    init: >
      export PREVIEW_FULL_URL=`gp url 8001` &&
      export PREVIEW_URL=${PREVIEW_FULL_URL#"https://"} &&
      cp .gitpod/blt.yml blt/local.blt.yml &&
      composer install --no-interaction &&
      blt blt:telemetry:disable --no-interaction &&
      blt settings &&
      blt drupal:install -n
    command: |
      apache2ctl restart
      gp await-port 8001
      find docroot -name 'local.drush.yml' | xargs rm &&
      export PREVIEW_FULL_URL=`gp url 8001` &&
      export PREVIEW_URL=${PREVIEW_FULL_URL#"https://"} &&
      blt settings
      drush uli
      drush uli | xargs gp preview --external
      git config core.fileMode false
      blt blt:telemetry:disable --no-interaction
