ports:
  - name: database
    description: Mysql database
    port: 3306
    onOpen: ignore
    visibility: private
  - port: 33060
    onOpen: ignore
    visibility: private
  - name: drupal
    description: Drupal backend layer
    port: 8001
    onOpen: ignore
    visibility: public
  - name: frontend
    description: NextJS frontend layer
    port: 3000
    onOpen: ignore
    visibility: public
  - port: 8002-9999
    onOpen: ignore
image:
  file: .gitpod.Dockerfile
tasks:
  - name: Drupal Prep
    init: >
      export PREVIEW_FULL_URL=`gp url 8001` &&
      export PREVIEW_URL=${PREVIEW_FULL_URL#"https://"} &&
      cp .gitpod/blt.yml blt/local.blt.yml &&
      git checkout composer.* &&
      composer install --no-interaction &&
      blt blt:telemetry:disable --no-interaction &&
      blt settings &&
      blt drupal:install -n
    command: |
      cd $GITPOD_REPO_ROOT &&
      echo 'Restarting Apache' &&
      apache2ctl restart &&
      gp ports await 8001 &&
      find docroot -name 'local.drush.yml' | xargs rm &&
      export PREVIEW_FULL_URL=`gp url 8001` &&
      export PREVIEW_URL=${PREVIEW_FULL_URL#"https://"} &&
      blt blt:telemetry:disable --no-interaction &&
      echo 'Establishing Settings' &&
      blt settings &&
      echo 'Logging Into Drupal' &&
      drush st &&
      echo "drush uli --uri=$PREVIEW_FULL_URL" &&
      drush uli --uri=$PREVIEW_FULL_URL &&
      echo "drush uli --uri=$PREVIEW_FULL_URL | xargs gp preview --external" &&
      drush uli --uri=$PREVIEW_FULL_URL | xargs gp preview --external &&
      git config core.fileMode false
  - name: SSH Keys
    before: |
      mkdir -p ~/.ssh
      if [[ ! -z $SSH_PUBLIC_KEY  ]]; then
          echo $SSH_PUBLIC_KEY | base64 -d > ~/.ssh/id_rsa.pub && chmod 644 ~/.ssh/id_rsa.pub
      fi
      if [[ ! -z $SSH_PRIVATE_KEY ]]; then
          echo $SSH_PRIVATE_KEY | base64 -d > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
      fi
      if [[ ! -z $GITCONFIG ]]; then
          echo $GITCONFIG | base64 -d > ~/.gitconfig && chmod 644 ~/.gitconfig
      fi
vscode:
  extensions:
    - bradlc.vscode-tailwindcss
