github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: false
    addComment: false
    addBadge: false
ports:
  - port: 3306
    onOpen: ignore
    visibility: private
  - port: 33060
    onOpen: ignore
    visibility: private
  - port: 8001
    onOpen: ignore
    visibility: public
  - port: 3000
    onOpen: ignore
    visibility: public
image: pookmish/drupal8ci:gitpod
tasks:
  - name: Drupal Prep
    before: >
      rm -rf ~/.ssh/id_rsa &&
      rm -rf ~/.ssh/id_rsa.pub &&
      eval $(command gp env -e) &&
      mkdir -p ~/.ssh &&
      [[ ! -z $SSH_PUBLIC_KEY  ]] &&
      echo $SSH_PUBLIC_KEY | base64 -d > ~/.ssh/id_rsa.pub &&
      chmod 644 ~/.ssh/id_rsa.pub &&
      [[ ! -z $SSH_PRIVATE_KEY  ]] &&
      echo $SSH_PRIVATE_KEY | base64 -d > ~/.ssh/id_rsa &&
      chmod 600 ~/.ssh/id_rsa &&
      [[ ! -z $GITCONFIG  ]] &&
      echo $GITCONFIG | base64 -d > ~/.gitconfig &&
      chmod 644 ~/.gitconfig
    init: >
      export PREVIEW_FULL_URL=`gp url 8001` &&
      export PREVIEW_URL=${PREVIEW_FULL_URL#"https://"} &&
      cp .gitpod/blt.yml blt/local.blt.yml &&
      composer install --no-interaction &&
      blt blt:telemetry:disable --no-interaction &&
      blt settings &&
      blt drupal:install -n &&
      git clone git@github.com:SU-SWS/sulgryphon-nextjs.git frontend &&
      cd frontend && yarn && 
      cp .env.example .env.local &&
      sed -i -e "s|\${NEXT_PUBLIC_DRUPAL_BASE_URL}|${PREVIEW_FULL_URL}|g" .env.local &&
      sed -i -e "s|\${NEXT_IMAGE_DOMAIN}|${PREVIEW_URL}|g" .env.local &&
      sed -i -e "s|\${NEXT_PUBLIC_SITE_NAME}|Gitpod|g" .env.local &&
      sed -i -e "s|\${DRUPAL_FRONT_PAGE}|${PREVIEW_FULL_URL}|g" .env.local &&
      sed -i -e "s|\${DRUPAL_PREVIEW_SECRET}|${PREVIEW_FULL_URL}|g" .env.local &&
      sed -i -e "s|\${DRUPAL_CLIENT_ID}|${PREVIEW_FULL_URL}|g" .env.local &&
      sed -i -e "s|\${DRUPAL_CLIENT_SECRET}|${PREVIEW_FULL_URL}|g" .env.local &&
      yarn dev &
    command: |
      apache2ctl restart
      gp await-port 8001
      find docroot -name 'local.drush.yml' | xargs rm &&
      export PREVIEW_FULL_URL=`gp url 8001` &&
      export PREVIEW_URL=${PREVIEW_FULL_URL#"https://"} &&
      blt settings
      drush uli
      drush uli | xargs gp preview --external
      git config core.fileMode false
      blt blt:telemetry:disable --no-interaction
  - name: Frontend Prep
    init: >
