<?php


$fields = ["author_1_first_name",
"author_1_following",
"author_1_last_name",
"author_1_middle",
"author_1_preceding",
"author_1_role",
"author_2_first_name",
"author_2_following",
"author_2_last_name",
"author_2_middle",
"author_2_preceding",
"author_2_role",
"author_3_first_name",
"author_3_following",
"author_3_last_name",
"author_3_middle",
"author_3_preceding",
"author_3_role",
"author_4_first_name",
"author_4_following",
"author_4_last_name",
"author_4_middle",
"author_4_preceding",
"author_4_role",
"author_info",
"authors_full",
"availability_description",
"catalog_month",
"catalog_page",
"catalog_season_yyyy",
"cloth_sale_percent",
"cloth_sale_price",
"copublisher_name",
"copublisher_yn",
"copyright",
"description",
"digital_comp_link",
"html_page_title",
"illustrations",
"imprint",
"in_print_status",
"instructor_recommeded",
"isbn_13_alt",
"isbn_13_cloth",
"isbn_13_digital",
"isbn_13_isw",
"isbn_13_paper",
"local_web_blurb",
"new_paperback_yn",
"pages",
"paper_sale_percent",
"paper_sale_price",
"price_cloth",
"price_digital",
"price_paper",
"print_desk_copies",
"pub_date_cloth",
"pub_date_digital",
"pub_date_first",
"pub_date_paper",
"pub_year_first",
"reviews",
"rights_description",
"sales_rank",
"series",
"status_cloth",
"status_digital",
"status_paper",
"subtitle",
"table_of_contents",
"url_isw",
"web_code_cloth",
"web_code_paper",
"work_id_number"];


foreach ($fields as $field){
  echo ( 'sup_' . $field . ': ' . $field . PHP_EOL);
}

