<?php

/**
 * @file
 * Primary module hooks for Summer Helper module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Component\Utility\Html;

/**
 * Implements hook_paragraphs_behavior_info_alter().
 */
function summer_helper_paragraphs_behavior_info_alter(&$paragraphs_behavior) {
  $paragraphs_behavior['su_card_styles']['class'] = '\Drupal\summer_helper\Plugin\paragraphs\Behavior\SummerCardBehaviors';
}

/**
 * Implements hook_page_attachments().
 */
function summer_helper_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'summer_helper/admin';
}

/**
 * Implements hook_library_info_alter().
 */
function summer_helper_library_info_alter(&$libraries, $extension) {
  if ($extension === 'ckeditor5') {
    $module_path = \Drupal::service('extension.list.module')
      ->getPath('summer_helper');
    $libraries['internal.drupal.ckeditor5.stylesheets'] = [
      'css' => [
        'theme' => [
          "/$module_path/styles/dist/css/ckeditor.css" => [],
        ],
      ],
    ];
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function summer_helper_form_summer_entity_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $status_element = &$form['status']['widget']['value'];
  $status_element['#states'] = [
    'disabled' => [':input[name="publish_on[0][value][time]"]' => ['filled' => TRUE]],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function summer_helper_preprocess_paragraph(&$variables) {
  /** @var \Drupal\paragraphs\ParagraphInterface $paragraph */
  $paragraph = $variables['paragraph'];
  $variables['attributes']['class'][] = Html::cleanCssIdentifier('paragraph-' . $paragraph->bundle());
}
