<?php

/**
 * @file
 * Primary module hooks for Summer Helper module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_paragraphs_behavior_info_alter().
 */
function summer_helper_paragraphs_behavior_info_alter(&$paragraphs_behavior) {
  $paragraphs_behavior['su_card_styles']['class'] = '\Drupal\summer_helper\Plugin\paragraphs\Behavior\SummerCardBehaviors';
}

/**
 * Implements hook_page_attachments().
 */
function summer_helper_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'summer_helper/admin';
}

/**
 * Implements hook_library_info_alter().
 */
function summer_helper_library_info_alter(&$libraries, $extension) {
  if ($extension === 'ckeditor5') {
    $module_path = \Drupal::service('extension.list.module')
      ->getPath('summer_helper');
    $libraries['internal.drupal.ckeditor5.stylesheets'] = [
      'css' => [
        'theme' => [
          "/$module_path/styles/dist/css/ckeditor.css" => [],
        ],
      ],
    ];
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function summer_helper_form_summer_entity_form_alter(&$form, FormStateInterface $form_state, $form_id) {
//  $scheduler_increment = \Drupal::state()
//    ->get('stanford_profile_helper.scheduler_increment', 60 * 60 * 4);
//  $hours = (int) floor($scheduler_increment / 3600);
//  $mins = (int) floor($scheduler_increment / 60 % 60);
//  $scheduler_increment = $hours ? "$hours hour(s)" : "$mins minute(s)";
//  $example_start = new DateTime('today 8:00 AM');
//  $example_end = clone $example_start;
//  if ($hours > 0) {
//    $example_end->modify("+$hours hours");
//  }
//  $example_end->modify("+$mins minutes");
}
