adding:
  dependencies:
    config:
      - filter.format.sum_markdown
      - node.type.sum_summer_courses
  permissions:
    - 'create sum_summer_courses content'
    - 'delete any stanford_event_series content'
    - 'delete any stanford_policy content'
    - 'delete any sum_summer_courses content'
    - 'delete own sum_summer_courses content'
    - 'delete stanford_event_series revisions'
    - 'delete stanford_policy revisions'
    - 'delete sum_summer_courses revisions'
    - 'edit any sum_summer_courses content'
    - 'edit own sum_summer_courses content'
    - 'revert stanford_page revisions'
    - 'revert sum_summer_courses revisions'
    - 'use text format sum_markdown'
    - 'view any unpublished sum_summer_courses content'
    - 'view sum_summer_courses revisions'
removing:
  permissions:
    - 'create stanford_event content'
    - 'create stanford_news content'
    - 'create stanford_person content'
    - 'create stanford_publication content'
    - 'delete own stanford_event content'
    - 'delete own stanford_news content'
    - 'delete own stanford_person content'
    - 'edit any stanford_course content'
    - 'edit any stanford_event content'
    - 'edit any stanford_event_series content'
    - 'edit any stanford_news content'
    - 'edit any stanford_person content'
    - 'edit any stanford_policy content'
    - 'edit any stanford_publication content'
    - 'edit own stanford_course content'
    - 'edit own stanford_event content'
    - 'edit own stanford_event_series content'
    - 'edit own stanford_news content'
    - 'edit own stanford_person content'
    - 'edit own stanford_policy content'
    - 'edit own stanford_publication content'
    - 'view stanford_course revisions'
    - 'view stanford_event revisions'
    - 'view stanford_event_series revisions'
    - 'view stanford_news revisions'
    - 'view stanford_person revisions'
    - 'view stanford_publication revisions'
