adding:
  dependencies:
    config:
      - filter.format.sum_markdown
      - node.type.sum_summer_courses
      - taxonomy.vocabulary.sum_course_availability
      - taxonomy.vocabulary.sum_course_interest_area
      - taxonomy.vocabulary.sum_course_population
      - taxonomy.vocabulary.sum_summer_courses
  permissions:
    - 'create sum_summer_courses content'
    - 'create terms in sum_course_availability'
    - 'create terms in sum_course_interest_area'
    - 'create terms in sum_course_population'
    - 'create terms in sum_summer_courses'
    - 'delete any sum_summer_courses content'
    - 'delete own sum_summer_courses content'
    - 'delete sum_summer_courses revisions'
    - 'delete terms in sum_course_availability'
    - 'delete terms in sum_course_interest_area'
    - 'delete terms in sum_course_population'
    - 'delete terms in sum_summer_courses'
    - 'edit any sum_summer_courses content'
    - 'edit own sum_summer_courses content'
    - 'edit terms in sum_course_availability'
    - 'edit terms in sum_course_interest_area'
    - 'edit terms in sum_course_population'
    - 'edit terms in sum_summer_courses'
    - 'revert sum_summer_courses revisions'
    - 'use text format sum_markdown'
    - 'view any unpublished sum_summer_courses content'
    - 'view sum_summer_courses revisions'
removing:
  permissions:
    - 'create stanford_course content'
    - 'create stanford_event content'
    - 'create stanford_event_series content'
    - 'create stanford_news content'
    - 'create stanford_person content'
    - 'create stanford_policy content'
    - 'create stanford_publication content'
    - 'create terms in stanford_news_topics'
    - 'edit any stanford_course content'
    - 'edit any stanford_event content'
    - 'edit any stanford_event_series content'
    - 'edit any stanford_news content'
    - 'edit any stanford_person content'
    - 'edit any stanford_policy content'
    - 'edit any stanford_publication content'
