adding:
  dependencies:
    config:
      - field.field.node.summer_courses.sum_catalog_number
      - field.field.node.summer_courses.sum_course_catalog_number
      - field.field.node.summer_courses.sum_course_cross_listing
      - field.field.node.summer_courses.sum_course_description
      - field.field.node.summer_courses.sum_course_instructors
      - field.field.node.summer_courses.sum_course_interest_area
      - field.field.node.summer_courses.sum_course_name
      - field.field.node.summer_courses.sum_course_notes
      - field.field.node.summer_courses.sum_course_prerequisites
      - field.field.node.summer_courses.sum_course_units
    module:
      - text
  content:
    sum_catalog_number:
      type: string
      label: above
      settings:
        link_to_entity: false
      third_party_settings: {  }
      weight: 104
      region: content
    sum_course_catalog_number:
      type: string
      label: above
      settings:
        link_to_entity: false
      third_party_settings: {  }
      weight: 108
      region: content
    sum_course_cross_listing:
      type: string
      label: above
      settings:
        link_to_entity: false
      third_party_settings: {  }
      weight: 112
      region: content
    sum_course_description:
      type: text_default
      label: above
      settings: {  }
      third_party_settings: {  }
      weight: 107
      region: content
    sum_course_instructors:
      type: string
      label: above
      settings:
        link_to_entity: false
      third_party_settings: {  }
      weight: 109
      region: content
    sum_course_interest_area:
      type: entity_reference_label
      label: above
      settings:
        link: true
      third_party_settings: {  }
      weight: 113
      region: content
    sum_course_name:
      type: string
      label: above
      settings:
        link_to_entity: false
      third_party_settings: {  }
      weight: 102
      region: content
    sum_course_notes:
      type: text_default
      label: above
      settings: {  }
      third_party_settings: {  }
      weight: 106
      region: content
    sum_course_prerequisites:
      type: text_default
      label: above
      settings: {  }
      third_party_settings: {  }
      weight: 111
      region: content
    sum_course_units:
      type: number_integer
      label: above
      settings:
        thousand_separator: ''
        prefix_suffix: true
      third_party_settings: {  }
      weight: 110
      region: content
removing: {  }
