adding:
  dependencies:
    config:
      - filter.format.sum_markdown
      - node.type.sum_summer_courses
      - taxonomy.vocabulary.sum_course_availability
      - taxonomy.vocabulary.sum_course_interest_area
      - taxonomy.vocabulary.sum_course_population
      - taxonomy.vocabulary.sum_summer_courses
    module:
      - stanford_migrate
  permissions:
    - 'create sum_summer_courses content'
    - 'create terms in sum_course_availability'
    - 'create terms in sum_course_interest_area'
    - 'create terms in sum_course_population'
    - 'create terms in sum_summer_courses'
    - 'delete any sum_summer_courses content'
    - 'delete own sum_summer_courses content'
    - 'delete sum_summer_courses revisions'
    - 'delete terms in sum_course_availability'
    - 'delete terms in sum_course_interest_area'
    - 'delete terms in sum_course_population'
    - 'delete terms in sum_summer_courses'
    - 'edit any sum_summer_courses content'
    - 'edit own sum_summer_courses content'
    - 'edit terms in sum_course_availability'
    - 'edit terms in sum_course_interest_area'
    - 'edit terms in sum_course_population'
    - 'edit terms in sum_summer_courses'
    - 'import sum_csv_summer_courses migration'
    - 'revert sum_summer_courses revisions'
    - 'use text format sum_markdown'
    - 'view any unpublished sum_summer_courses content'
    - 'view sum_summer_courses revisions'
removing:
  dependencies:
    config:
      - taxonomy.vocabulary.event_audience
      - taxonomy.vocabulary.stanford_event_types
      - taxonomy.vocabulary.stanford_news_topics
      - taxonomy.vocabulary.stanford_person_types
      - taxonomy.vocabulary.stanford_publication_topics
    module:
      - book
  permissions:
    - 'add content to books'
    - 'administer book outlines'
    - 'administer news-topics menu items'
    - 'administer stanford-event-types menu items'
    - 'administer stanford-person-type menu items'
    - 'create new books'
    - 'create stanford_course content'
    - 'create stanford_event content'
    - 'create stanford_event_series content'
    - 'create stanford_news content'
    - 'create stanford_person content'
    - 'create stanford_policy content'
    - 'create stanford_publication content'
    - 'create terms in event_audience'
    - 'create terms in stanford_event_types'
    - 'create terms in stanford_news_topics'
    - 'create terms in stanford_person_types'
    - 'create terms in stanford_publication_topics'
    - 'delete any stanford_course content'
    - 'delete any stanford_event content'
    - 'delete any stanford_event_series content'
    - 'delete any stanford_news content'
    - 'delete any stanford_person content'
    - 'delete any stanford_publication content'
    - 'delete terms in event_audience'
    - 'delete terms in stanford_event_types'
    - 'delete terms in stanford_news_topics'
    - 'delete terms in stanford_person_types'
    - 'delete terms in stanford_publication_topics'
    - 'edit any stanford_course content'
    - 'edit any stanford_event content'
    - 'edit any stanford_event_series content'
    - 'edit any stanford_news content'
    - 'edit any stanford_person content'
    - 'edit any stanford_policy content'
    - 'edit any stanford_publication content'
    - 'edit own stanford_course content'
    - 'edit own stanford_event content'
    - 'edit own stanford_event_series content'
    - 'edit own stanford_news content'
    - 'edit own stanford_person content'
    - 'edit own stanford_policy content'
    - 'edit own stanford_publication content'
    - 'edit terms in event_audience'
    - 'edit terms in stanford_event_types'
    - 'edit terms in stanford_news_topics'
    - 'edit terms in stanford_person_types'
    - 'edit terms in stanford_publication_topics'
    - 'revert stanford_course revisions'
    - 'revert stanford_event revisions'
    - 'revert stanford_event_series revisions'
    - 'revert stanford_news revisions'
    - 'revert stanford_person revisions'
    - 'revert stanford_policy revisions'
    - 'revert stanford_publication revisions'
