adding:
  dependencies:
    config:
      - field.field.paragraph.at_a_glance.sum_at_a_glance_descrip
      - field.field.paragraph.at_a_glance.sum_at_a_glance_headline
    module:
      - text
  content:
    sum_at_a_glance_descrip:
      type: text_textarea
      weight: 1
      region: content
      settings:
        rows: 5
        placeholder: ''
      third_party_settings: {  }
    sum_at_a_glance_headline:
      type: string_textfield
      weight: 0
      region: content
      settings:
        size: 60
        placeholder: ''
      third_party_settings: {  }
removing: {  }
