adding:
  dependencies:
    config:
      - field.field.config_pages.stanford_basic_site_settings.su_site_algolia_ui
      - field.field.config_pages.stanford_basic_site_settings.sum_site_header_prim
      - field.field.config_pages.stanford_basic_site_settings.sum_site_header_sec
  content:
    sum_site_header_prim:
      type: link
      label: above
      settings:
        trim_length: 80
        url_only: false
        url_plain: false
        rel: ''
        target: ''
      third_party_settings: {  }
      weight: 25
      region: content
    sum_site_header_sec:
      type: link
      label: above
      settings:
        trim_length: 80
        url_only: false
        url_plain: false
        rel: ''
        target: ''
      third_party_settings: {  }
      weight: 26
      region: content
removing: {  }
