adding:
  content:
    su_global_msg_header:
      weight: 1
    su_global_msg_link:
      weight: 3
    su_global_msg_message:
      weight: 2
  hidden:
    su_global_msg_label: true
    su_global_msg_type: true
removing:
  content:
    su_global_msg_header:
      weight: 3
    su_global_msg_label:
      type: string_textfield
      weight: 2
      region: content
      settings:
        size: 60
        placeholder: ''
      third_party_settings: {  }
    su_global_msg_link:
      weight: 5
    su_global_msg_message:
      weight: 4
    su_global_msg_type:
      type: options_select
      weight: 1
      region: content
      settings: {  }
      third_party_settings: {  }
