adding: {  }
removing:
  dependencies:
    config:
      - field.field.config_pages.stanford_global_message.su_global_msg_type
  content:
    su_global_msg_type:
      type: options_select
      weight: 1
      region: content
      settings: {  }
      third_party_settings: {  }
