adding:
  permissions:
    config_split_sequence_1_s3dub4tgfmf0af2j: 'access content'
    config_split_sequence_2_s3dub4tgfmf0af2j: 'access content'
    config_split_sequence_3_s3dub4tgfmf0af2j: 'access content'
    config_split_sequence_4_s3dub4tgfmf0af2j: 'access content'
removing: {  }
