adding:
  dependencies:
    config:
      - filter.format.sum_markdown
      - node.type.sum_summer_courses
  permissions:
    - 'create sum_summer_courses content'
    - 'edit any sum_summer_courses content'
    - 'edit own sum_summer_courses content'
    - 'revert stanford_policy revisions'
    - 'revert sum_summer_courses revisions'
    - 'use text format sum_markdown'
    - 'view sum_summer_courses revisions'
removing:
  permissions:
    - 'create stanford_event content'
    - 'create stanford_news content'
    - 'create stanford_person content'
    - 'create stanford_publication content'
