adding:
  content:
    su_page_banner:
      type: layout_paragraphs
      settings:
        preview_view_mode: default
        nesting_depth: 0
        require_layouts: 0
        empty_message: ''
        view_mode: default
    su_page_components:
      settings:
        preview_view_mode: sum_editing_preview
        view_mode: default
        form_display_mode: default
      third_party_settings:
        change_labels:
          field_label_overwrite: ''
          hide_add_another: 0
          force_single_cardinality: 0
removing:
  dependencies:
    module:
      - paragraphs
  content:
    su_page_banner:
      type: paragraphs
      settings:
        title: Paragraph
        title_plural: Paragraphs
        edit_mode: closed
        closed_mode: preview
        autocollapse: none
        closed_mode_threshold: 0
        add_mode: dropdown
        default_paragraph_type: _none
        features:
          add_above: '0'
          collapse_edit_all: '0'
          convert: '0'
          duplicate: '0'
    su_page_components:
      settings:
        preview_view_mode: default
