adding:
  dependencies:
    config:
      - paragraphs.paragraphs_type.sum_top_banner
  settings:
    handler_settings:
      target_bundles:
        sum_top_banner: sum_top_banner
      target_bundles_drag_drop:
        sum_calculator:
          weight: 32
          enabled: false
        sum_course_filter:
          weight: 33
          enabled: false
        sum_top_banner:
          weight: 34
          enabled: true
        sum_user_favorites:
          weight: 35
          enabled: false
        sum_video:
          weight: 36
          enabled: false
removing: {  }
