adding:
  dependencies:
    config:
      - core.entity_view_display.node.stanford_page.default
      - filter.format.sum_markdown
      - node.type.sum_summer_courses
  permissions:
    - 'configure all stanford_page node layout overrides'
    - 'configure editable stanford_page node layout overrides'
    - 'create sum_summer_courses content'
    - 'edit any sum_summer_courses content'
    - 'edit own sum_summer_courses content'
    - 'revert sum_summer_courses revisions'
    - 'use text format sum_markdown'
    - 'view sum_summer_courses revisions'
removing: {  }
