adding:
  dependencies:
    config:
      - field.field.node.summer_courses.sum_course_availability
      - field.field.node.summer_courses.sum_course_catalog_number
      - field.field.node.summer_courses.sum_course_class_number
      - field.field.node.summer_courses.sum_course_course_cost
      - field.field.node.summer_courses.sum_course_cross_listing
      - field.field.node.summer_courses.sum_course_description
      - field.field.node.summer_courses.sum_course_end_date
      - field.field.node.summer_courses.sum_course_format
      - field.field.node.summer_courses.sum_course_instructors
      - field.field.node.summer_courses.sum_course_interest_area
      - field.field.node.summer_courses.sum_course_length
      - field.field.node.summer_courses.sum_course_name
      - field.field.node.summer_courses.sum_course_notes
      - field.field.node.summer_courses.sum_course_population
      - field.field.node.summer_courses.sum_course_prerequisites
      - field.field.node.summer_courses.sum_course_schedule
      - field.field.node.summer_courses.sum_course_start_date
      - field.field.node.summer_courses.sum_course_syllabus_file
      - field.field.node.summer_courses.sum_course_unique_import_id
      - field.field.node.summer_courses.sum_course_units
      - field.field.node.summer_courses.sum_students_also_studied
  hidden:
    sum_course_availability: true
    sum_course_catalog_number: true
    sum_course_class_number: true
    sum_course_course_cost: true
    sum_course_cross_listing: true
    sum_course_description: true
    sum_course_end_date: true
    sum_course_format: true
    sum_course_instructors: true
    sum_course_interest_area: true
    sum_course_length: true
    sum_course_name: true
    sum_course_notes: true
    sum_course_population: true
    sum_course_prerequisites: true
    sum_course_schedule: true
    sum_course_start_date: true
    sum_course_syllabus_file: true
    sum_course_unique_import_id: true
    sum_course_units: true
    sum_students_also_studied: true
removing: {  }
