adding:
  dependencies:
    config:
      - core.entity_view_display.node.stanford_page.default
      - filter.format.sum_markdown
  permissions:
    - 'configure all stanford_page node layout overrides'
    - 'configure editable stanford_page node layout overrides'
    - 'use text format sum_markdown'
removing:
  permissions:
    - 'create terms in stanford_event_types'
    - 'create terms in stanford_news_topics'
    - 'create terms in stanford_person_types'
    - 'create terms in stanford_publication_topics'
