adding:
  dependencies:
    config:
      - field.field.paragraph.at_a_glance.sum_at_a_glance_descrip
      - field.field.paragraph.at_a_glance.sum_at_a_glance_facts
      - field.field.paragraph.at_a_glance.sum_at_a_glance_headline
      - field.field.paragraph.at_a_glance.sum_at_a_glance_link
    module:
      - link
      - paragraphs
      - text
  content:
    sum_at_a_glance_descrip:
      type: text_textarea
      weight: 1
      region: content
      settings:
        rows: 5
        placeholder: ''
      third_party_settings: {  }
    sum_at_a_glance_facts:
      type: paragraphs
      weight: 2
      region: content
      settings:
        title: Paragraph
        title_plural: Paragraphs
        edit_mode: open
        closed_mode: summary
        autocollapse: none
        closed_mode_threshold: 0
        add_mode: dropdown
        form_display_mode: default
        default_paragraph_type: ''
        features:
          collapse_edit_all: collapse_edit_all
          duplicate: duplicate
      third_party_settings: {  }
    sum_at_a_glance_headline:
      type: string_textfield
      weight: 0
      region: content
      settings:
        size: 60
        placeholder: ''
      third_party_settings: {  }
    sum_at_a_glance_link:
      type: link_default
      weight: 3
      region: content
      settings:
        placeholder_url: ''
        placeholder_title: ''
      third_party_settings: {  }
removing: {  }
