adding: {  }
removing:
  dependencies:
    config:
      - views.view.stanford_courses
  third_party_settings:
    layout_builder:
      sections:
        -
          components:
            00d6e3fa-7393-4fef-a92d-da1ecbeb1af0:
              uuid: 00d6e3fa-7393-4fef-a92d-da1ecbeb1af0
              region: main
              configuration:
                id: 'views_block:stanford_courses-taxonomy_term_page_list'
                label: ''
                label_display: '0'
                provider: views
                context_mapping: {  }
                views_label: ''
                items_per_page: none
              weight: 4
              additional: {  }
