adding:
  entity_config:
    node:
      sum_summer_courses:
        enabled: true
        query_load_enabled: true
        edges_enabled: true
        routes_enabled: true
    paragraph:
      sum_accordions:
        enabled: true
      sum_calculator:
        enabled: true
      sum_course_filter:
        enabled: true
      sum_user_favorites:
        enabled: true
      sum_video:
        enabled: true
        query_load_enabled: true
      sum_top_banner:
        enabled: true
    taxonomy_term:
      sum_course_availability:
        enabled: true
      sum_course_interest_area:
        enabled: true
      sum_course_population:
        enabled: true
  field_config:
    config_pages:
      stanford_basic_site_settings:
        sum_site_header_prim:
          enabled: true
        sum_site_header_sec:
          enabled: true
    node:
      sum_summer_courses:
        sum_course_availability:
          enabled: true
        sum_course_catalog_number:
          enabled: true
        sum_course_class_number:
          enabled: true
        sum_course_course_cost:
          enabled: true
        sum_course_cross_listing:
          enabled: true
        sum_course_description:
          enabled: true
        sum_course_end_date:
          enabled: true
        sum_course_format:
          enabled: true
        sum_course_image:
          enabled: true
        sum_course_instructors:
          enabled: true
        sum_course_interest_area:
          enabled: true
        sum_course_length:
          enabled: true
        sum_course_notes:
          enabled: true
        sum_course_population:
          enabled: true
        sum_course_prerequisites:
          enabled: true
        sum_course_schedule:
          enabled: true
        sum_course_start_date:
          enabled: true
        sum_course_syllabus_file:
          enabled: true
        sum_course_unique_import_id:
          enabled: true
        sum_course_units:
          enabled: true
        sum_students_also_studied:
          enabled: true
    paragraph:
      sum_accordions:
        sum_accordions_accords:
          enabled: true
        sum_accordions_desc:
          enabled: true
        sum_accordions_heading:
          enabled: true
      sum_calculator:
        sum_calc_app_fee:
          enabled: true
        sum_calc_books:
          enabled: true
        sum_calc_commute_help:
          enabled: true
        sum_calc_documents:
          enabled: true
        sum_calc_grad_app_help:
          enabled: true
        sum_calc_grad_unit_cost:
          enabled: true
        sum_calc_grad_unit_help:
          enabled: true
        sum_calc_health_fee:
          enabled: true
        sum_calc_high_app_help:
          enabled: true
        sum_calc_high_unit_cost:
          enabled: true
        sum_calc_high_unit_help:
          enabled: true
        sum_calc_house_fees:
          enabled: true
        sum_calc_house_help:
          enabled: true
        sum_calc_i20_fee:
          enabled: true
        sum_calc_i20_help:
          enabled: true
        sum_calc_ins_help:
          enabled: true
        sum_calc_ins_wave_help:
          enabled: true
        sum_calc_insurance:
          enabled: true
        sum_calc_mail_fee:
          enabled: true
        sum_calc_meals:
          enabled: true
        sum_calc_prog_fee:
          enabled: true
        sum_calc_tech_fee:
          enabled: true
        sum_calc_ug_app_help:
          enabled: true
        sum_calc_ug_unit_cost:
          enabled: true
        sum_calc_ug_unit_help:
          enabled: true
      sum_top_banner:
        sum_top_banner_cards:
          enabled: true
        sum_top_banner_descrip:
          enabled: true
        sum_top_banner_headline:
          enabled: true
        sum_top_banner_image:
          enabled: true
        sum_top_banner_link:
          enabled: true
        sum_top_banner_superhead:
          enabled: true
      sum_video:
        sum_video_video:
          enabled: true
removing:
  entity_config:
    paragraph:
      stanford_accordion:
        query_load_enabled: true
