adding:
  dependencies:
    config:
      - paragraphs.paragraphs_type.sum_accordions
      - paragraphs.paragraphs_type.sum_at_a_glance
      - paragraphs.paragraphs_type.sum_calculator
      - paragraphs.paragraphs_type.sum_carousel
      - paragraphs.paragraphs_type.sum_course_filter
      - paragraphs.paragraphs_type.sum_pill_banner
      - paragraphs.paragraphs_type.sum_user_favorites
      - paragraphs.paragraphs_type.sum_video
  settings:
    handler_settings:
      target_bundles:
        sum_course_filter: sum_course_filter
        sum_calculator: sum_calculator
        sum_user_favorites: sum_user_favorites
        sum_accordions: sum_accordions
        sum_video: sum_video
        sum_carousel: sum_carousel
        sum_at_a_glance: sum_at_a_glance
        sum_pill_banner: sum_pill_banner
      target_bundles_drag_drop:
        stanford_page_title_banner:
          weight: 24
          enabled: false
        sum_accordions:
          weight: 33
          enabled: true
        sum_arc_banner:
          weight: 36
          enabled: false
        sum_at_a_glance:
          weight: 40
          enabled: true
        sum_calculator:
          weight: 30
          enabled: true
        sum_carousel:
          weight: 38
          enabled: true
        sum_course_filter:
          weight: 29
          enabled: true
        sum_facts:
          weight: 44
          enabled: false
        sum_pill_banner:
          weight: 50
          enabled: true
        sum_slide_teaser:
          weight: 45
          enabled: false
        sum_top_banner:
          weight: 34
          enabled: false
        sum_user_favorites:
          weight: 30
          enabled: true
        sum_video:
          weight: 34
          enabled: true
removing: {  }
