name: lagunita
recipe: drupal10
config:
  webroot: docroot
  php: '8.2'
  xdebug: false
proxy:
  appserver:
    - lagunita.lndo.site
    - supress.lndo.site
  adminer:
    - adminer.lagunita.lndo.site
services:
  appserver:
    build_as_root:
      - pecl install pcov
      - docker-php-ext-enable pcov
    build:
      - composer install
    volumes:
      - ~/.acquia:/var/www/.acquia
    ssl: true
    config:
      php: lando/php.ini
      # Uncomment the below for behat testing
      overrides:
        environment:
          MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", {"browserName":"chrome","chromeOptions":{"args":["--disable-gpu","--headless"]}}, "http://chromedriver:4444"]'
          BEHAT_PARAMS: >-
            {
              "extensions" : {
                "Behat\\MinkExtension" : {
                  "base_url" : "http://lagunita.lndo.site/"
                }
              }
            }
  database:
    creds:
      user: drupal
      password: drupal
      database: drupal
  adminer:
    type: compose
    services:
      image: dehy/adminer
      command: /bin/s6-svscan /etc/services.d
    portforward: true
  cardinalservice:
    type: mysql:5.7
    creds:
      user: drupal
      password: drupal
      database: sulgryphon
  #  gryphon:
  #    creds:
  #      user: drupal
  #      password: drupal
  #      database: gryphon
  # Uncomment the below for behat testing.
  chromedriver:
    type: lando
    api: 3
    ssl: false
    sslExpose: false
    services:
      user: root
      image: selenium/standalone-chrome:115.0
      command: /opt/bin/entry_point.sh
      volumes:
        - /dev/shm:/dev/shm
      ports:
        - 4444
tooling:
  blt:
    service: appserver
    cmd: /app/vendor/bin/blt
  git:
    service: appserver
  phpcs:
    service: appserver
    cmd: "/app/vendor/bin/phpcs --standard=Drupal,DrupalPractice"
    options:
    description: Run phpcs for given folder or file.
  phpunit:
    service: appserver
    cmd: "/app/vendor/bin/phpunit -c /app/docroot/core"
    description: Run phpunit tests
  codeception:
    service: appserver
    cmd: "/app/vendor/bin/blt tests:codeception:run"
