adding:
  dependencies:
    config:
      - field.field.paragraph.stanford_lists.sup_list_eyebrow
  content:
    status:
      weight: 5
    su_list_button:
      weight: 4
    su_list_description:
      weight: 3
    su_list_headline:
      weight: 2
    sup_list_eyebrow:
      type: string_textfield
      weight: 1
      region: content
      settings:
        size: 60
        placeholder: ''
      third_party_settings: {  }
removing:
  content:
    status:
      weight: 4
    su_list_button:
      weight: 3
    su_list_description:
      weight: 2
    su_list_headline:
      weight: 1
