adding:
  dependencies:
    config:
      - field.field.config_pages.stanford_basic_site_settings.su_site_algolia_ui
      - field.field.config_pages.stanford_basic_site_settings.sup_filemaker_pass
      - field.field.config_pages.stanford_basic_site_settings.sup_filemaker_user
  content:
    sup_filemaker_pass:
      type: string
      label: above
      settings:
        link_to_entity: false
      third_party_settings: {  }
      weight: 26
      region: content
    sup_filemaker_user:
      type: string
      label: above
      settings:
        link_to_entity: false
      third_party_settings: {  }
      weight: 25
      region: content
removing: {  }
