adding:
  settings:
    allowed_views:
      sup_books: sup_books
      stanford_shared_tags: '0'
      change_logs: '0'
      stanford_courses: '0'
      editoria11y_dismissals: '0'
      editoria11y_results: '0'
      stanford_events: '0'
      authmap: '0'
      stanford_news: '0'
      stanford_person: '0'
      policies: '0'
      stanford_publications: '0'
      samlauth_map: '0'
      taxonomy_term_pages: '0'
    allowed_display_types:
      graphql: '0'
removing:
  settings:
    allowed_views:
      stanford_courses: stanford_courses
      stanford_events: stanford_events
      stanford_news: stanford_news
      stanford_person: stanford_person
      stanford_publications: stanford_publications
      stanford_shared_tags: stanford_shared_tags
      stanford_event_terms_utility: '0'
      stanford_news_terms: '0'
      stanford_person_list_terms_first: '0'
      stanford_person_terms: '0'
      publication_terms: '0'
