adding:
  dependencies:
    config:
      - media.type.sup_protected_file
      - node.type.sup_book
      - node.type.sup_book_ancillary
  permissions:
    - 'create sup_book content'
    - 'create sup_book_ancillary content'
    - 'create sup_protected_file media'
    - 'delete own sup_book content'
    - 'delete own sup_book_ancillary content'
    - 'delete own sup_protected_file media'
    - 'edit any sup_book content'
    - 'edit any sup_book_ancillary content'
    - 'edit any sup_protected_file media'
    - 'edit own sup_book content'
    - 'edit own sup_book_ancillary content'
    - 'edit own sup_protected_file media'
    - 'view any unpublished sup_book content'
    - 'view any unpublished sup_book_ancillary content'
    - 'view sup_book revisions'
    - 'view sup_book_ancillary revisions'
removing:
  dependencies:
    config:
      - node.type.stanford_course
      - node.type.stanford_event
      - node.type.stanford_event_series
      - node.type.stanford_news
      - node.type.stanford_person
      - node.type.stanford_policy
      - node.type.stanford_publication
    module:
      - book
  permissions:
    - 'add content to books'
    - 'create stanford_event content'
    - 'create stanford_news content'
    - 'create stanford_person content'
    - 'create stanford_publication content'
    - 'delete own stanford_course content'
    - 'delete own stanford_event content'
    - 'delete own stanford_event_series content'
    - 'delete own stanford_news content'
    - 'delete own stanford_person content'
    - 'delete own stanford_policy content'
    - 'delete own stanford_publication content'
    - 'edit any stanford_course content'
    - 'edit any stanford_event content'
    - 'edit any stanford_event_series content'
    - 'edit any stanford_news content'
    - 'edit any stanford_person content'
    - 'edit any stanford_policy content'
    - 'edit any stanford_publication content'
    - 'edit own stanford_course content'
    - 'edit own stanford_event content'
    - 'edit own stanford_event_series content'
    - 'edit own stanford_news content'
    - 'edit own stanford_person content'
    - 'edit own stanford_policy content'
    - 'edit own stanford_publication content'
    - 'view any unpublished stanford_course content'
    - 'view any unpublished stanford_event content'
    - 'view any unpublished stanford_event_series content'
    - 'view any unpublished stanford_news content'
    - 'view any unpublished stanford_person content'
    - 'view any unpublished stanford_policy content'
    - 'view any unpublished stanford_publication content'
    - 'view stanford_course revisions'
    - 'view stanford_event revisions'
    - 'view stanford_event_series revisions'
    - 'view stanford_news revisions'
    - 'view stanford_person revisions'
    - 'view stanford_policy revisions'
    - 'view stanford_publication revisions'
