adding:
  dependencies:
    config:
      - field.field.paragraph.stanford_lists.sup_list_eyebrow
  content:
    sup_list_eyebrow:
      type: string
      label: above
      settings:
        link_to_entity: false
      third_party_settings: {  }
      weight: 4
      region: content
removing: {  }
