adding:
  dependencies:
    config:
      - field.field.paragraph.stanford_card.sup_card_link_style
      - field.field.paragraph.stanford_card.sup_card_style
      - field.field.paragraph.stanford_card.sup_heading_level
      - field.field.paragraph.stanford_card.sup_vis_hide_heading
  hidden:
    sup_card_link_style: true
    sup_card_style: true
    sup_heading_level: true
    sup_vis_hide_heading: true
removing: {  }
