adding:
  dependencies:
    config:
      - node.type.sup_book
      - taxonomy.vocabulary.sup_book_subjects
      - taxonomy.vocabulary.sup_book_tags
      - taxonomy.vocabulary.sup_file_groups
      - taxonomy.vocabulary.sup_imprints
      - taxonomy.vocabulary.sup_series
    module:
      - supress_helper
  permissions:
    - 'administer sup_award'
    - 'create sup_book content'
    - 'create terms in sup_book_subjects'
    - 'create terms in sup_book_tags'
    - 'create terms in sup_file_groups'
    - 'create terms in sup_imprints'
    - 'create terms in sup_series'
    - 'delete any sup_book content'
    - 'delete own sup_book content'
    - 'delete sup_book revisions'
    - 'delete terms in sup_book_subjects'
    - 'delete terms in sup_book_tags'
    - 'delete terms in sup_file_groups'
    - 'delete terms in sup_imprints'
    - 'delete terms in sup_series'
    - 'edit any sup_book content'
    - 'edit own sup_book content'
    - 'edit terms in sup_book_subjects'
    - 'edit terms in sup_book_tags'
    - 'edit terms in sup_file_groups'
    - 'edit terms in sup_imprints'
    - 'edit terms in sup_series'
    - 'revert sup_book revisions'
    - 'view sup_book revisions'
removing:
  dependencies:
    config:
      - node.type.stanford_course
      - node.type.stanford_event
      - node.type.stanford_event_series
      - node.type.stanford_news
      - node.type.stanford_person
      - node.type.stanford_policy
      - node.type.stanford_publication
      - taxonomy.vocabulary.event_audience
      - taxonomy.vocabulary.stanford_event_types
      - taxonomy.vocabulary.stanford_news_topics
      - taxonomy.vocabulary.stanford_person_types
      - taxonomy.vocabulary.stanford_publication_topics
  permissions:
    - 'create stanford_course content'
    - 'create stanford_event content'
    - 'create stanford_event_series content'
    - 'create stanford_news content'
    - 'create stanford_person content'
    - 'create stanford_policy content'
    - 'create stanford_publication content'
    - 'create terms in event_audience'
    - 'create terms in stanford_event_types'
    - 'create terms in stanford_news_topics'
    - 'create terms in stanford_person_types'
    - 'create terms in stanford_publication_topics'
    - 'delete any stanford_course content'
    - 'delete any stanford_event content'
    - 'delete any stanford_event_series content'
    - 'delete any stanford_news content'
    - 'delete any stanford_person content'
    - 'delete any stanford_policy content'
    - 'delete any stanford_publication content'
    - 'delete own stanford_course content'
    - 'delete own stanford_event content'
    - 'delete own stanford_event_series content'
    - 'delete own stanford_news content'
    - 'delete own stanford_person content'
    - 'delete own stanford_policy content'
    - 'delete own stanford_publication content'
    - 'delete stanford_course revisions'
    - 'delete stanford_event revisions'
    - 'delete stanford_event_series revisions'
    - 'delete stanford_news revisions'
    - 'delete stanford_person revisions'
    - 'delete stanford_policy revisions'
    - 'delete stanford_publication revisions'
    - 'delete terms in event_audience'
    - 'delete terms in stanford_event_types'
    - 'delete terms in stanford_news_topics'
    - 'delete terms in stanford_person_types'
    - 'delete terms in stanford_publication_topics'
    - 'edit any stanford_course content'
    - 'edit any stanford_event content'
    - 'edit any stanford_event_series content'
    - 'edit any stanford_news content'
    - 'edit any stanford_person content'
    - 'edit any stanford_policy content'
    - 'edit any stanford_publication content'
    - 'edit own stanford_course content'
    - 'edit own stanford_event content'
    - 'edit own stanford_event_series content'
    - 'edit own stanford_news content'
    - 'edit own stanford_person content'
    - 'edit own stanford_policy content'
    - 'edit own stanford_publication content'
    - 'edit terms in event_audience'
    - 'edit terms in stanford_event_types'
    - 'edit terms in stanford_news_topics'
    - 'edit terms in stanford_person_types'
    - 'edit terms in stanford_publication_topics'
    - 'revert stanford_course revisions'
    - 'revert stanford_event revisions'
    - 'revert stanford_event_series revisions'
    - 'revert stanford_news revisions'
    - 'revert stanford_person revisions'
    - 'revert stanford_policy revisions'
    - 'revert stanford_publication revisions'
    - 'view any unpublished stanford_course content'
    - 'view any unpublished stanford_event content'
    - 'view any unpublished stanford_event_series content'
    - 'view any unpublished stanford_news content'
    - 'view any unpublished stanford_person content'
    - 'view any unpublished stanford_policy content'
    - 'view any unpublished stanford_publication content'
    - 'view stanford_course revisions'
    - 'view stanford_event revisions'
    - 'view stanford_event_series revisions'
    - 'view stanford_news revisions'
    - 'view stanford_person revisions'
    - 'view stanford_policy revisions'
    - 'view stanford_publication revisions'
