adding:
  content:
    body:
      weight: 3
      region: content
    su_policy_authority:
      label: above
      weight: 2
      region: content
    su_policy_effective:
      label: above
      third_party_settings:
        field_formatter_class:
          class: ''
      weight: 0
      region: content
    su_policy_updated:
      label: above
      weight: 1
      region: content
removing:
  dependencies:
    module:
      - ds
      - empty_fields
  third_party_settings:
    ds:
      layout:
        id: ds_1col
        library: null
        disable_css: false
        entity_classes: all_classes
        settings:
          classes:
            layout_class: {  }
          wrappers:
            ds_content: div
          outer_wrapper: div
          attributes: ''
          link_attribute: ''
          link_custom: ''
          label: ''
      regions:
        ds_content:
          - node_title
          - su_policy_authority
          - su_policy_updated
          - su_policy_effective
          - body
      fields:
        node_title:
          plugin_id: node_title
          weight: 0
          label: hidden
          formatter: default
          settings:
            link: false
            'link class': ''
            link_target: ''
            wrapper: h1
            class: ''
  content:
    body:
      weight: 4
      region: ds_content
    su_policy_authority:
      label: inline
      weight: 1
      region: ds_content
    su_policy_effective:
      label: inline
      weight: 3
      region: ds_content
    su_policy_updated:
      label: inline
      third_party_settings:
        empty_fields:
          handler: ''
      weight: 2
      region: ds_content
