adding:
  dependencies:
    module:
      - filefield_paths
  third_party_settings:
    filefield_paths:
      enabled: true
      file_path:
        value: media/file
        options:
          slashes: false
          pathauto: false
          transliterate: false
      file_name:
        value: '[file:ffp-name-only-original].[file:ffp-extension-original]'
        options:
          slashes: false
          pathauto: false
          transliterate: false
      redirect: false
      retroactive_update: false
      active_updating: false
  settings:
    file_extensions: 'txt rtf doc docx ppt pptx xls xlsx pdf mp3 wav'
removing:
  settings:
    file_extensions: 'txt rtf doc docx ppt pptx xls xlsx pdf'
