adding: {  }
removing:
  dependencies:
    module:
      - jumpstart_ui
  behavior_plugins:
    hero_pattern:
      enabled: true
      overlay_position: left
      heading: h2
      hide_heading: false
