adding:
  settings:
    plugins:
      ckeditor5_style:
        styles:
          -
            label: Normal
            element: '<p class="plain-text">'
          -
            label: 'Intro Text'
            element: '<p class="su-intro-text">'
          -
            label: 'Splash Font'
            element: '<p class="su-font-splash">'
          -
            label: 'Quote Text'
            element: '<p class="su-quote-text">'
          -
            label: 'Drop Cap First Letter'
            element: '<p class="su-drop-cap">'
          -
            label: 'Card Text'
            element: '<p class="su-related-text">'
          -
            label: 'Callout Text'
            element: '<p class="su-callout-text">'
          -
            label: 'Sub Title'
            element: '<p class="su-subheading">'
removing: {  }
