adding:
  third_party_settings:
    layout_builder_restrictions:
      entity_view_mode_restriction:
        allowlisted_blocks:
          Menus:
            - 'menu_block:stanford-event-types'
            - 'system_menu_block:main'
            - 'menu_block:stanford-person-type'
            - 'menu_block:stanford-publication-topics'
            - 'menu_block:news-topics'
removing:
  third_party_settings:
    layout_builder:
      sections:
        -
          components:
            82a532c7-d73f-491e-8ce3-3fd27c29a815:
              configuration:
                formatter:
                  third_party_settings:
                    empty_fields:
                      handler: ''
                    field_label:
                      label_class: ''
                      label_value: ''
                      label_tag: ''
            e04c6120-8ac4-4ff0-bd25-8588de307dd1:
              configuration:
                formatter:
                  third_party_settings:
                    empty_fields:
                      handler: ''
                    field_label:
                      label_class: ''
                      label_value: ''
                      label_tag: h3
            8222e428-abc1-40e2-9309-e6ca03530c1f:
              configuration:
                formatter:
                  third_party_settings:
                    empty_fields:
                      handler: ''
                    field_label:
                      label_class: ''
                      label_value: ''
                      label_tag: ''
