<?php

/**
 * @file
 * Primary module hooks for SUL Helper module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Session\AccountInterface;
use Drupal\paragraphs\ParagraphInterface;

/**
 * Implements hook_paragraphs_behavior_info_alter().
 */
function sul_helper_paragraphs_behavior_info_alter(&$paragraphs_behavior) {
  $paragraphs_behavior['su_card_styles']['class'] = '\Drupal\sul_helper\Plugin\paragraphs\Behavior\SuCardStylesBehaviors';
}

/**
 * Implements hook_ENTITY_TYPE_create_access().
 */
function sul_helper_paragraph_create_access(AccountInterface $account, array $context, $entity_bundle) {
  return AccessResult::forbiddenIf($entity_bundle == 'stanford_gallery');
}

/**
 * Implements hook_entity_type_alter().
 */
function sul_helper_entity_type_alter(array &$entity_types) {
  /** @var \Drupal\Core\Entity\EntityTypeInterface[] $entity_types */
  $entity_types['paragraph']->setLinkTemplate('canonical', '/admin/paragraph/{paragraph}');
  $entity_types['paragraph']->setHandlerClass('route_provider', ['html' => '\Drupal\Core\Entity\Routing\AdminHtmlRouteProvider']);
}

/**
 * Implements hook_next_site_preview_alter().
 */
function sul_helper_next_site_preview_alter(array &$preview, array $context) {
  $accepted_previews = ['node', 'paragraph'];
  if (!in_array($context['entity']->getEntityTypeid(), $accepted_previews)) {
    $preview = $context['original_build'][0]['content'];
  }
}

/**
 * Implements hook_entity_display_build_alter().
 */
function sul_helper_entity_display_build_alter(&$build, $context) {
  $current_route = \Drupal::routeMatch()->getRouteName();
  $allowed_routes = [
    'layout_paragraphs.builder.insert',
    'layout_paragraphs.builder.edit_item',
    'entity.node.edit_form',
  ];

  if (!in_array($current_route, $allowed_routes) || !($context['entity'] instanceof ParagraphInterface)) {
    return;
  }
  \Drupal::service('sul_helper.jsonapi_serializer')
    ->alterEntityBuild($build, $context['entity'], $context['display']);
}

/**
 * Implements hook_ckeditor_css_alter().
 */
function sul_helper_ckeditor_css_alter(array &$css) {
  $module_path = \Drupal::service('extension.list.module')
    ->getPath('sul_helper');
  $css[] = "$module_path/css/wysiwyg.css";
}

/**
 * Implements hook_library_info_alter().
 */
function sul_helper_library_info_alter(&$libraries, $extension) {
  if ($extension == 'layout_paragraphs') {
    $libraries['builder']['dependencies'][] = 'sul_helper/layout_paragraphs';
  }
  if ($extension == 'node') {
    $libraries['drupal.node']['dependencies'][] = 'sul_helper/node_form';
  }
}
/**
 * Implements hook_field_widget_WIDGET_TYPE_form_alter().
 */
function sul_helper_field_widget_viewfield_select_form_alter(&$element, FormStateInterface $form_state, $context) {
  $element['view_options']['arguments']['#title'] = t('Filtering Arguments (taxonomy terms)');
}

/**
 * Implements hook_preprocess_HOOK().
 */
function sul_helper_preprocess_paragraph__stanford_spacer(&$variables) {
  // Copied from stanford_basic theme.
  $paragraph = $variables['elements']['#paragraph'];
  if ($paragraph->hasField('su_spacer_size') && !$paragraph->get('su_spacer_size')->isEmpty()) {
    $variables['attributes']['class'][] = $paragraph->get('su_spacer_size')->getString();
  }
}

/**
 * Implements hook_graphql_compose_field_type_alter().
 */
function sul_helper_graphql_compose_field_type_alter(array &$field_types) {
  $field_types['link']['class'] = 'Drupal\sul_helper\Plugin\GraphQLCompose\FieldType\SulLinkItem';
}

/**
 * Implements hook_graphql_compose_graphql_type_alter().
 */
function sul_helper_graphql_compose_graphql_type_alter(array &$entity_types) {
  $entity_types['Link']['class'] = 'Drupal\sul_helper\Plugin\GraphQLCompose\SchemaType\SulLinkType';
}
