#!/bin/bash

# Navigate to the local repository
cd /path/to/local/repository

# Get the date and time of the last Git pull
last_pull=$(git log --max-count=1 --format=%cd --date=format:"%Y-%m-%d %H:%M:%S" origin/master)

# Get the changes made to the src folder since the last pull
changes=$(git log --since="$last_pull" --oneline -- src/)

# Print the changes
echo "$changes"
