adding:
  dependencies:
    module:
      - change_labels
      - link_attributes
  content:
    su_media_caption_link:
      type: link_attributes
      weight: 2
      region: content
      settings:
        enabled_attributes:
          aria-label: true
          id: false
          name: false
          target: false
          rel: false
          class: false
          accesskey: false
          title: false
      third_party_settings:
        change_labels:
          field_label_overwrite: ''
removing:
  dependencies:
    module:
      - link
  content:
    su_media_caption_link:
      type: link_default
      weight: 4
