adding:
  dependencies:
    config:
      - field.field.node.stanford_event.sul_event__image
    module:
      - media_library
  third_party_settings:
    field_group:
      group_editorial_content:
        weight: 3
      group_body_content:
        weight: 4
      group_event_details:
        weight: 5
      group_schedule_details:
        weight: 6
      group_taxonomy:
        weight: 9
  content:
    publish_on:
      weight: 12
    status:
      weight: 7
    su_event_components:
      type: paragraphs
      settings:
        title: Paragraph
        title_plural: Paragraphs
        edit_mode: closed
        closed_mode: summary
        autocollapse: all
        closed_mode_threshold: 0
        add_mode: dropdown
        form_display_mode: default
        default_paragraph_type: _none
        features:
          add_above: '0'
          collapse_edit_all: '0'
          duplicate: duplicate
    su_event_date_time:
      settings:
        separator: to
    su_event_groups:
      settings:
        formatter_third_party_settings: {  }
    su_event_keywords:
      settings:
        formatter_third_party_settings: {  }
    su_event_subject:
      settings:
        formatter_third_party_settings: {  }
    su_metatags:
      weight: 10
    sul_event__image:
      type: media_library_widget
      weight: 2
      region: content
      settings:
        media_types: {  }
      third_party_settings: {  }
    unpublish_on:
      type: datetime_timestamp_no_default
      weight: 54
      region: content
      settings: {  }
      third_party_settings: {  }
removing:
  dependencies:
    config:
      - field.field.node.stanford_event.layout_builder__layout
      - field.field.node.stanford_event.su_event_ext_image
    module:
      - change_labels
      - layout_paragraphs
  third_party_settings:
    field_group:
      group_editorial_content:
        weight: 2
      group_body_content:
        weight: 3
      group_event_details:
        weight: 4
      group_schedule_details:
        weight: 5
      group_taxonomy:
        weight: 11
  content:
    publish_on:
      weight: 52
    status:
      weight: 6
    su_event_components:
      type: layout_paragraphs
      settings:
        preview_view_mode: default
        nesting_depth: 0
        require_layouts: 1
        empty_message: ''
      third_party_settings:
        change_labels:
          add_another: ''
    su_metatags:
      weight: 12
  hidden:
    layout_builder__layout: true
    unpublish_on: true
