adding:
  source:
    data_parser_plugin: sul_localist_json
    fields:
      -
        name: event_id
      -
        name: first_date
        label: first_date
        selector: event/first_date
      -
        name: last_date
        label: last_date
        selector: event/last_date
      -
        name: url
        label: url
        selector: event/urls
      -
        name: location_name
        label: 'Location Name'
        selector: event/location_name
      -
        name: status
        label: Status
        selector: event/status
      -
        name: keywords
        label: 'Keywords Array'
        selector: event/keywords
      -
        name: tags
        label: 'Tags Array'
        selector: event/tags
      -
        name: description
        label: Description
        selector: event/description
      -
        name: geo_latitude
        label: 'Geo Latitutde'
        selector: event/geo/latitude
      -
        name: geo_longitude
        label: 'Geo Longitude'
        selector: event/geo/longitude
      -
        name: geo_street
        label: 'Geo Street'
        selector: event/geo/street
      -
        name: geo_city
        label: 'Geo City'
        selector: event/geo/city
      -
        name: geo_state
        label: 'Geo State'
        selector: event/geo/state
      -
        name: geo_country
        label: 'Geo Country'
        selector: event/geo/country
      -
        name: geo_zip
        label: 'Geo Zip'
        selector: event/geo/zip
      -
        name: event_audience
        label: 'Event Audience'
        selector: event/filters/event_audience
      -
        name: event_subject
        label: 'Event Subject'
        selector: event/filters/event_subject
      -
        name: event_types
        label: 'Event Types'
        selector: event/filters/event_types
      -
        name: localist_url
        label: 'Localist URL'
        selector: event/localist_url
      -
        name: photo_url
        label: 'Photo URL'
        selector: event/photo_url
      -
        name: event_instance_start
        label: 'Event Instance Start'
        selector: event/event_instances/0/event_instance/start
      -
        name: event_instance_end
        label: 'Event Instance End'
        selector: event/event_instances/0/event_instance/end
      -
        name: groups
        label: Groups
        selector: event/groups
      -
        name: departments
        label: Departments
        selector: event/departments
    ids:
      event_id:
        type: string
    constants:
      alt: ''
      image_tag: Localist
  process:
    su_event_map_link/uri:
      -
        plugin: skip_on_empty
        source: geo_zip
        method: process
      -
        plugin: concat
        source:
          - constants/map_link_base
          - geo_street
          - constants/plus
          - geo_city
          - constants/plus
          - geo_state
          - constants/plus
          - geo_zip
    start_time:
      plugin: str_replace
      regex: true
      source: event_instance_start
      search: '/.*(T.*)-.*$/'
      replace: $1
    end_time:
      -
        plugin: null_coalesce
        source:
          - event_instance_end
          - event_instance_start
      -
        plugin: str_replace
        regex: true
        search: '/.*(T.*)-.*$/'
        replace: $1
      -
        plugin: str_replace
        search: '00:00:00'
        replace: '23:59:00'
    su_event_date_time/value:
      -
        plugin: concat
        source:
          - first_date
          - '@start_time'
      -
        plugin: format_date
        from_format: 'Y-m-d\TH:i:s'
        to_format: U
        from_timezone: America/Los_Angeles
    su_event_date_time/end_value:
      -
        plugin: concat
        source:
          - last_date
          - '@end_time'
      -
        plugin: format_date
        from_format: 'Y-m-d\TH:i:s'
        to_format: U
        from_timezone: America/Los_Angeles
    image_file:
      -
        plugin: skip_on_empty
        method: process
        source: photo_url
      -
        plugin: file_import
        destination: constants/image_path
        id_only: true
        reuse: true
    media_tag:
      plugin: entity_generate
      value_key: name
      bundle_key: vid
      bundle: media_tags
      entity_type: taxonomy_term
      ignore_case: true
      source: constants/image_tag
    sul_event__image/target_id:
      -
        plugin: skip_on_empty
        method: process
        source: photo_url
      -
        plugin: skip_on_empty
        method: process
        source: '@image_file'
      -
        plugin: entity_generate
        source: '@image_file'
        value_key: field_media_image
        bundle_key: bundle
        bundle: image
        entity_type: media
        ignore_case: true
        values:
          name: title
          field_media_image/target_id: '@image_file'
          field_media_image/alt: constants/alt
          su_media_category/target_id: '@media_tag'
  destination:
    overwrite_properties:
      - sul_event__image/target_id
removing:
  source:
    data_parser_plugin: json
    fields:
      -
        name: id
      -
        name: title
        label: Title
        selector: event/title
      -
        name: url
        label: url
        selector: event/url
      -
        name: updated_at
        label: 'Updated At'
        selector: event/updated_at
      -
        name: created_at
        label: 'Created At'
        selector: event/created_at
      -
        name: facebook_id
        label: 'Facebook ID'
        selector: event/facebook_id
      -
        name: first_date
        label: 'First Date'
        selector: event/first_date
      -
        name: last_date
        label: 'Last Date'
        selector: event/last_date
      -
        name: hashtag
        label: Hashtag
        selector: event/hashtag
      -
        name: urlname
        label: 'URL Name'
        selector: event/urlname
      -
        name: user_id
        label: 'User ID'
        selector: event/user_id
      -
        name: directions
        label: Directions
        selector: event/directions
      -
        name: location
        label: Location
        selector: event/location
      -
        name: room_number
        label: 'Room Number'
        selector: event/room_number
      -
        name: location_name
        label: 'Location Name'
        selector: event/location_name
      -
        name: status
        label: Status
        selector: event/status
      -
        name: experience
        label: Experience
        selector: event/experience
      -
        name: stream_url
        label: 'Stream URL'
        selector: event/stream_url
      -
        name: stream_info
        label: 'Stream Info'
        selector: event/stream_info
      -
        name: stream_embed_code
        label: 'Stream Embed Code'
        selector: event/stream_embed_code
      -
        name: created_by
        label: 'Created By'
        selector: event/created_by
      -
        name: updated_by
        label: 'Updated By'
        selector: event/updated_by
      -
        name: city_id
        label: 'City ID'
        selector: event/city_id
      -
        name: neighborhood_id
        label: 'Neighborhood ID'
        selector: event/neighborhood_id
      -
        name: school_id
        label: 'School ID'
        selector: event/school_id
    ids:
      event_instance_id:
        type: string
  process:
    su_event_map_link/uri:
      -
        plugin: concat
        source:
          - constants/map_link_base
          - geo_street
          - constants/plus
          - geo_city
          - constants/plus
          - geo_state
          - constants/plus
          - geo_zip
    su_event_date_time/value:
      -
        plugin: callback
        callable: strtotime
        source: event_instance_start
    su_event_date_time/end_value:
      -
        plugin: null_coalesce
        source:
          - event_instance_end
          - event_instance_start
      -
        plugin: callback
        callable: strtotime
      -
        plugin: smartdate_adjust
        start_time: '@su_event_date_time/value'
    su_event_date_time/duration:
      -
        plugin: stanford_events_datemath
        operation: subtraction
        source: event_instance_end
        values:
          - event_instance_start
