adding:
  uuid: 9ceb02fa-f83f-4d67-ad94-8874150e0131
  resourceFields:
    sul_image_credit:
      disabled: false
      fieldName: sul_image_credit
      publicName: sul_image_credit
      enhancer:
        id: ''
removing:
  uuid: a8d0f3a3-7684-4b25-a0c9-f08fa5446a01
