adding:
  resourceFields:
    metatag:
      disabled: false
    su_metatags:
      disabled: false
removing:
  resourceFields:
    metatag:
      disabled: true
    layout_builder__layout:
      disabled: true
      fieldName: layout_builder__layout
      publicName: layout_builder__layout
      enhancer:
        id: ''
    su_metatags:
      disabled: true
