adding:
  uuid: f60771b4-ba6a-490e-8c4c-efe6e2f5d0b5
  resourceFields:
    tid:
      disabled: false
    vid:
      disabled: true
removing:
  uuid: 21faf8a1-0a95-49e1-8716-2fe31668580b
  dependencies:
    module:
      - jsonapi_defaults
  third_party_settings:
    jsonapi_defaults:
      default_include:
        - parent
      page_limit: 50
  resourceFields:
    tid:
      disabled: true
    vid:
      disabled: false
    layout_builder__layout:
      disabled: true
      fieldName: layout_builder__layout
      publicName: layout_builder__layout
      enhancer:
        id: ''
