adding:
  resourceFields:
    metatag:
      disabled: false
    field_menulink:
      disabled: false
    su_metatags:
      disabled: false
removing:
  third_party_settings:
    jsonapi_defaults:
      default_include:
        - layout_selection
  resourceFields:
    metatag:
      disabled: true
    field_menulink:
      disabled: true
    layout_builder__layout:
      disabled: true
      fieldName: layout_builder__layout
      publicName: layout_builder__layout
      enhancer:
        id: ''
    su_metatags:
      disabled: true
