adding:
  uuid: 6d4f8acd-4fff-4971-91a9-89dbacf4bf23
  resourceFields:
    metatag:
      disabled: true
      fieldName: metatag
      publicName: metatag
      enhancer:
        id: ''
removing:
  uuid: afb40414-7681-4498-b430-5a35cde47e61
