adding:
  uuid: ac7fb085-a947-45cf-97fa-ce63ed3f76c4
  resourceFields:
    metatag:
      disabled: true
      fieldName: metatag
      publicName: metatag
      enhancer:
        id: ''
removing:
  uuid: 0294bd9c-56de-4089-ad35-d69bd689866b
