adding:
  third_party_settings:
    jsonapi_defaults:
      default_include:
        - su_list_view
  resourceFields:
    metatag:
      disabled: true
      fieldName: metatag
      publicName: metatag
      enhancer:
        id: ''
removing: {  }
