adding:
  uuid: 96fa3f55-dab5-49ff-bdfb-efbf856a03c3
  resourceFields:
    tid:
      disabled: false
    vid:
      disabled: true
removing:
  uuid: 46ca3da4-8223-4917-8885-94958418c1df
  dependencies:
    module:
      - jsonapi_defaults
  third_party_settings:
    jsonapi_defaults:
      default_include:
        - parent
      page_limit: 50
  resourceFields:
    tid:
      disabled: true
    vid:
      disabled: false
    layout_builder__layout:
      disabled: true
      fieldName: layout_builder__layout
      publicName: layout_builder__layout
      enhancer:
        id: ''
