adding:
  uuid: a980fe15-28c9-4a3c-8ec2-951c19420bcd
  resourceFields:
    su_local_foot_action:
      enhancer:
        id: ''
    su_local_foot_f_url:
      enhancer:
        id: ''
    su_local_foot_loc_img:
      enhancer:
        id: ''
    su_local_foot_loc_link:
      enhancer:
        id: ''
    su_local_foot_primary:
      enhancer:
        id: ''
    su_local_foot_second:
      enhancer:
        id: ''
    su_local_foot_social:
      enhancer:
        id: ''
removing:
  uuid: 8035fe36-ff7d-4e03-b9b7-235d125f459b
  third_party_settings:
    jsonapi_defaults:
      default_include:
        - su_local_foot_loc_img
  resourceFields:
    su_local_foot_action:
      enhancer:
        id: url_link
        settings:
          absolute_url: 0
    su_local_foot_f_url:
      enhancer:
        id: url_link
        settings:
          absolute_url: 0
    su_local_foot_loc_img:
      enhancer:
        id: url_link
        settings:
          absolute_url: 0
    su_local_foot_loc_link:
      enhancer:
        id: url_link
        settings:
          absolute_url: 0
    su_local_foot_primary:
      enhancer:
        id: url_link
        settings:
          absolute_url: 0
    su_local_foot_second:
      enhancer:
        id: url_link
        settings:
          absolute_url: 0
    su_local_foot_social:
      enhancer:
        id: url_link
        settings:
          absolute_url: 0
