adding:
  dependencies:
    module:
      - paragraphs
  content:
    path:
      weight: 10
    publish_on:
      weight: 12
    su_metatags:
      weight: 8
    su_news_components:
      type: entity_reference_paragraphs
      settings:
        title: Paragraph
        title_plural: Paragraphs
        edit_mode: closed
        add_mode: dropdown
        form_display_mode: default
        default_paragraph_type: stanford_wysiwyg
    su_news_hide_social:
      weight: 9
    su_shared_tags:
      weight: 7
    unpublish_on:
      type: datetime_timestamp_no_default
      weight: 54
      region: content
      settings: {  }
      third_party_settings: {  }
removing:
  dependencies:
    config:
      - field.field.node.stanford_news.layout_builder__layout
    module:
      - change_labels
      - layout_paragraphs
  content:
    path:
      weight: 12
    publish_on:
      weight: 52
    su_metatags:
      weight: 10
    su_news_components:
      type: layout_paragraphs
      settings:
        preview_view_mode: default
        nesting_depth: 0
        require_layouts: 1
        empty_message: ''
      third_party_settings:
        change_labels:
          add_another: ''
    su_news_hide_social:
      weight: 11
    su_shared_tags:
      weight: 9
  hidden:
    layout_builder__layout: true
    unpublish_on: true
