adding:
  uuid: 055b399c-7907-4040-aa68-c36558e3ae25
  resourceFields:
    tid:
      disabled: false
    vid:
      disabled: true
removing:
  uuid: 0b212d23-3346-42da-87f2-e21a4c27f26f
  dependencies:
    module:
      - jsonapi_defaults
  third_party_settings:
    jsonapi_defaults:
      default_include:
        - parent
      page_limit: 50
  resourceFields:
    tid:
      disabled: true
    vid:
      disabled: false
