adding:
  uuid: 1b105b2d-dcfb-478c-8dd6-592152a95b6e
  resourceFields:
    tid:
      disabled: false
    vid:
      disabled: true
removing:
  uuid: 89437034-dfb5-4e02-b2cf-16ab1c80bfc6
  dependencies:
    module:
      - jsonapi_defaults
  third_party_settings:
    jsonapi_defaults:
      default_include:
        - parent
      page_limit: 50
  resourceFields:
    tid:
      disabled: true
    vid:
      disabled: false
    su_cap_org_code:
      disabled: false
      fieldName: su_cap_org_code
      publicName: su_cap_org_code
      enhancer:
        id: ''
