adding:
  uuid: 6312c8fe-713e-493e-9dfa-34f342d97402
  resourceFields:
    uuid:
      disabled: true
    langcode:
      disabled: false
    status:
      disabled: false
    dependencies:
      disabled: false
    third_party_settings:
      disabled: false
    _core:
      disabled: false
    targetEntityType:
      disabled: false
    targetBundle:
      disabled: false
removing:
  uuid: 89fab672-c55a-44b0-a22e-32dcfbc71309
  resourceFields:
    uuid:
      disabled: false
    langcode:
      disabled: true
    status:
      disabled: true
    dependencies:
      disabled: true
    third_party_settings:
      disabled: true
    _core:
      disabled: true
    targetEntityType:
      disabled: true
    targetBundle:
      disabled: true
