adding:
  source:
    constants:
      email_domain: '@stanford.edu'
      law_email_domain: '@law.stanford.edu'
    fields:
      -
        name: searchTokens
        label: searchTokens
        selector: searchTokens
      -
        name: last_name
        label: 'Last Name'
        selector: names/preferred/lastName
      -
        name: first_name
        label: 'First Name'
        selector: names/preferred/firstName
      -
        name: short_title
        label: 'CAP Short Title'
        selector: shortTitle/title
      -
        name: long_title
        label: 'CAP Long Title'
        selector: longTitle/title
      -
        name: bio_html
        label: Biography
        selector: bio/html
      -
        name: email
        label: Email
        selector: primaryContact/email
      -
        name: mailcode
        label: 'Mail Code'
        selector: ldapAdditionalInfo/mailCode
      -
        name: alias
        label: Alias
        selector: alias
      -
        name: profile_photo
        label: 'Profile Photo'
        selector: profilePhotos/bigger/url
      -
        name: large_profile_photo
        label: 'Large Profile Photo'
        selector: profilePhotos/350x522/url
      -
        name: appointments
        label: 'Administrative Appointments'
        selector: longTitle/label/text
      -
        name: links
        label: 'Internet Links'
        selector: internetLinks
      -
        name: phone
        label: 'Phone Numbers'
        selector: primaryContact/phoneNumbers
      -
        name: office
        label: 'Office Locations'
        selector: contacts
      -
        name: profile_id
        label: 'Profile ID'
        selector: profileId
      -
        name: education
        label: Education
        selector: education
      -
        name: current_research_interests
        label: 'Research Interests'
        selector: currentResearchInterests/shortText.html
      -
        name: etag
        label: 'CAP API Etag'
        selector: meta/etag
      -
        name: academic_appts
        label: 'Academic Appointments'
        selector: academicOffices/0/position
      -
        name: admin_appts
        label: 'Administrative Appointments'
        selector: administrativeAppointments
      -
        name: research_interest_topics
        label: 'Research Interest Topics'
        selector: researchInterestTopics
      -
        name: scholarly_interests_fulltext
        label: 'Scholarly and Research Interests'
        selector: currentResearchInterests/fullText/html
      -
        name: scholarly_interests_tersetext
        selector: currentResearchInterests/terseText/html
      -
        name: community
        label: community
        selector: community
  process:
    nosave_email:
      -
        plugin: skip_on_empty
        source: sunetid
        method: process
      -
        plugin: concat
        source:
          - sunetid
          - constants/email_domain
    alias_email:
      -
        plugin: skip_on_empty
        source: alias
        method: process
      -
        plugin: concat
        source:
          - alias
          - constants/email_domain
    law_email:
      -
        plugin: skip_on_empty
        source: alias
        method: process
      -
        plugin: concat
        source:
          - alias
          - constants/law_email_domain
    libcal_email:
      -
        plugin: skip_on_empty
        source:
          - email
          - '@nosave_email'
          - '@alias_email'
          - '@law_email'
        method: process
      -
        plugin: libcal_lookup
    libcal_search:
      -
        plugin: skip_on_empty
        source: searchTokens
        method: process
      -
        plugin: libcal_lookup
    sul_person__libcal_id:
      plugin: null_coalesce
      source:
        - '@libcal_email'
        - '@libcal_search'
    libguide_email:
      -
        plugin: skip_on_empty
        method: process
        source:
          - email
          - '@nosave_email'
          - '@alias_email'
          - '@law_email'
      -
        plugin: libguide_lookup
    libguide_search:
      -
        plugin: skip_on_empty
        source: searchTokens
        method: process
      -
        plugin: libguide_lookup
    sul_person__libguide_id:
      plugin: null_coalesce
      source:
        - '@libguide_email'
        - '@libguide_search'
  destination:
    overwrite_properties:
      - sul_person__libcal_id
      - sul_person__libguide_id
removing:
  source:
    fields:
      -
        name: sunetid
        label: sunetid
        selector: uid
      -
        name: display_name
        label: 'Display Name'
        selector: displayName
      -
        name: last_name
        label: 'Last Name'
        selector: names/preferred/lastName
      -
        name: first_name
        label: 'First Name'
        selector: names/preferred/firstName
      -
        name: short_title
        label: 'CAP Short Title'
        selector: shortTitle/title
      -
        name: long_title
        label: 'CAP Long Title'
        selector: longTitle/title
      -
        name: bio_html
        label: Biography
        selector: bio/html
      -
        name: email
        label: Email
        selector: primaryContact/email
      -
        name: mailcode
        label: 'Mail Code'
        selector: ldapAdditionalInfo/mailCode
      -
        name: alias
        label: Alias
        selector: alias
      -
        name: profile_photo
        label: 'Profile Photo'
        selector: profilePhotos/bigger/url
      -
        name: large_profile_photo
        label: 'Large Profile Photo'
        selector: profilePhotos/350x522/url
      -
        name: appointments
        label: 'Administrative Appointments'
        selector: longTitle/label/text
      -
        name: links
        label: 'Internet Links'
        selector: internetLinks
      -
        name: phone
        label: 'Phone Numbers'
        selector: primaryContact/phoneNumbers
      -
        name: office
        label: 'Office Locations'
        selector: contacts
      -
        name: profile_id
        label: 'Profile ID'
        selector: profileId
      -
        name: education
        label: Education
        selector: education
      -
        name: current_research_interests
        label: 'Research Interests'
        selector: currentResearchInterests/shortText.html
      -
        name: etag
        label: 'CAP API Etag'
        selector: meta/etag
      -
        name: academic_appts
        label: 'Academic Appointments'
        selector: academicOffices/0/position
      -
        name: admin_appts
        label: 'Administrative Appointments'
        selector: administrativeAppointments
      -
        name: research_interest_topics
        label: 'Research Interest Topics'
        selector: researchInterestTopics
      -
        name: scholarly_interests_fulltext
        selector: currentResearchInterests/fullText/html
      -
        name: scholarly_interests_tersetext
        label: 'Scholarly and Research Interests'
        selector: currentResearchInterests/terseText/html
      -
        name: community
        label: community
        selector: community
