adding:
  third_party_settings:
    field_group:
      group_page_metadata:
        weight: 9
  content:
    field_menulink:
      weight: 14
    layout_selection:
      weight: 6
    publish_on:
      weight: 11
    stanford_intranet__access:
      weight: 8
    su_metatags:
      weight: 10
    su_page_components:
      settings:
        empty_message: Empty
      third_party_settings:
        change_labels:
          add_another: 'Add another item'
          field_label_overwrite: ''
    unpublish_on:
      type: datetime_timestamp_no_default
      weight: 13
      region: content
      settings: {  }
      third_party_settings: {  }
  hidden:
    su_page_banner: true
removing:
  dependencies:
    config:
      - field.field.node.stanford_page.layout_builder__layout
    module:
      - paragraphs
  third_party_settings:
    field_group:
      group_page_metadata:
        weight: 10
  content:
    field_menulink:
      weight: 26
    layout_selection:
      weight: 8
    publish_on:
      weight: 13
    stanford_intranet__access:
      weight: 9
    su_metatags:
      weight: 11
    su_page_components:
      settings:
        empty_message: ''
      third_party_settings:
        change_labels:
          add_another: ''
  hidden:
    layout_builder__layout: true
    unpublish_on: true
