adding:
  dependencies:
    config:
      - field.field.media.image.sul_image_credit
  content:
    sul_image_credit:
      type: string
      label: hidden
      settings:
        link_to_entity: false
      third_party_settings: {  }
      weight: 1
      region: content
removing: {  }
