adding:
  uuid: 4947512f-b10b-4bf7-b6e3-e0cda39d800e
  dependencies:
    module:
      - path
      - text
  content:
    description:
      type: text_textfield
      weight: 0
      region: content
      settings:
        size: 60
        placeholder: ''
      third_party_settings: {  }
    name:
      weight: -5
    path:
      type: path
      weight: 30
      region: content
      settings: {  }
      third_party_settings: {  }
    status:
      weight: 100
removing:
  uuid: 2cf25db6-2fc0-470a-b8cc-9e8757ad6366
  content:
    name:
      weight: 0
    status:
      weight: 1
  hidden:
    description: true
    path: true
