adding:
  uuid: 7d235aa4-9ad7-495b-ad30-4eb66d8e7050
  resourceFields:
    uri:
      enhancer:
        settings:
          style: blur
    status:
      disabled: true
removing:
  uuid: fb76e257-9c56-43a3-bf72-9a40822b3f20
  resourceFields:
    uri:
      enhancer:
        settings:
          style: tiny_blur
    status:
      disabled: false
