name: Deploy Main Artifact
on:
  workflow_run:
    workflows: ["Deploy Artifact"]
    types: [push]
    branches:
      - 'test-auto-deploy'
      - '1.x'
      - 'main'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  deploy:
    name: Deploy Main Artifact
    runs-on: ubuntu-latest
    env:
      DRUPAL_DATABASE_NAME: drupal
      DRUPAL_DATABASE_USERNAME: drupal
      DRUPAL_DATABASE_PASSWORD: drupal
      DRUPAL_DATABASE_HOST: mysql
    container:
      image: pookmish/drupal8ci:latest
    steps:
      - uses: actions/checkout@v3
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: |
            vendor
            docroot/core
            docroot/libraries
            docroot/modules/contrib
          key: 1.x-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
          restore-keys: |
            1.x-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
            1.x-${{ hashFiles('composer.json') }}-
            1.x-
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: fail
      - name: Deploy Artifact
        run: |
          git config --global user.email "sws-developers@lists.stanford.edu"
          git config --global user.name "Github Actions"
          ssh-keyscan -t rsa svn-45197.prod.hosting.acquia.com >> /root/.ssh/known_hosts
          composer install -n
          blt blt:telemetry:disable --no-interaction
          blt deploy -v -n
