# .github/workflows/release.yml
name: Release

on:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    if: github.event.pull_request.merged
    steps:
      - name: Get Next Release
        id: tag
        uses: K-Phoen/semver-release-action@master
        with:
          release_strategy: none
          release_branch: 2.x
          tag_format: "2.%minor%.%patch%"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo 'Creating new release for ' ${{ steps.tag.outputs.tag }}
      - name: Create Release
        if: ${{ steps.tag.outputs.tag }}
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ steps.tag.outputs.tag }}
          tag: ${{ steps.tag.outputs.tag }}
          commit: ${{ github.sha }}
          generateReleaseNotes: true
          makeLatest: true
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
      - run: |
          composer install -n
          DATE=`date +%Y-%m-%d`
          vendor/bin/blt deploy --tag=$(echo ${{ DATE }}_${{ steps.tag.outputs.tag }}) --commit-msg=${{ steps.tag.outputs.tag }} --no-interaction
